run-name: Build & Release

on: [push]

permissions:
  contents: write

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: "gh-cli auth login"
        run: gh auth login --with-token <<< "${{ github.token }}"

      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
        
      - name: "Build binaries"
        run: make build
      
      - name: "Release binaries"
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/dbdaddy-darwin-amd64
            bin/dbdaddy-darwin-arm64
            bin/dbdaddy-freebsd-amd64
            bin/dbdaddy-linux-386
            bin/dbdaddy-linux-amd64
            bin/dbdaddy-linux-arm64
            bin/dbdaddy-windows-386
            bin/dbdaddy-windows-amd64