run-name: Build & Release

on: [push]

permissions:
  contents: write

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: "gh-cli auth login"
        run: gh auth login --with-token <<< "${{ github.token }}"

      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
        
      - name: "Build binaries"
        run: make build

      - name: "Release binaries"
        run: make release
