run-name: Build & Release

on: [push]

permissions:
  contents: write
  issues: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: "gh-cli auth login"
        run: gh auth login --with-token <<< "${{ github.token }}"

      - name: "Checkout repo code"
        uses: actions/checkout@v4
        
      - name: "Build binaries"
        run: make build

      - name: "Release binaries"
        run: make release
