run-name: Build & Release

on: [push]

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: "LS"
        run: ls ${{ github.workspace }}
      - name: "Build binaries"
        run: make build

      - name: "Release binaries"
        run: make release
